name: CI Noc Documentation
on:
  push:
    branches:
      - main
permissions: write-all
      
jobs:
  noc:
    name: Generate the Noc documentation with nocdoc tool
    runs-on: ubuntu-latest

    steps:
    - uses: haskell/actions/setup@v1.2
    
    # Installing pandoc
    - run: sudo apt install pandoc
      name: Install pandoc
    
    # Build Noc
    - run: wget https://github.com/noc-lang/noc/releases/download/v0.1.0.0/noc-v0.1.0.0-patch.zip
      name: Download the Noc v0.1.0.0 release version
    - run: unzip ./noc-v0.1.0.0-patch.zip
    - run: make install
      working-directory: noc-v0.1.0.0-patch
      name: Building/Installing the Noc interpreter
    - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

    # Setup the Noc Manual
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - run: ./setup.sh
      name: Setup The Noc Manual (Convert the Markdown snippets in HTML with pandoc and build The Noc Manual with nocdoc)
    - run: mkdir noc_manual && mv manual noc_manual
    
    # Deploy the Noc Manual
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./noc_manual
